Repository facebook/TestSlide, pull requests merged in 2019-12, with the labels that each got.

#99 Add a flag to disable signature validation
  docs/strict_mock/index.rst
  tests/strict_mock_testslide.py
  testslide/strict_mock.py
Labels: CLA Signed

#100 Improve DSL docs on async checks
  docs/testslide_dsl/async_support/index.rst
Labels: CLA Signed, enhancement

#102 Add SlowCallback error type
  docs/testslide_dsl/async_support/index.rst
  tests/dsl_unittest.py
  testslide/__init__.py
Labels: CLA Signed

#104 Amend small bits of doc
  docs/testslide_dsl/async_support/index.rst
  tests/dsl_unittest.py
  testslide/__init__.py
Labels: CLA Signed

#106 Fix StrictMock with signature_validation=False
  tests/strict_mock_testslide.py
  testslide/strict_mock.py
Labels: CLA Signed, bug

#107 Disable async validation for builtins
  testslide/mock_callable.py
Labels: CLA Signed, enhancement
