Repository facebook/TestSlide, pull requests merged in 2020-05, with the labels that each got.

#185 Fix arguments validation logic
  testslide/lib.py
Labels: CLA Signed, bug

#184 Add file and line number for return type validation errors
  tests/lib_testslide.py
  tests/mock_callable_testslide.py
  testslide/lib.py
  testslide/mock_callable.py
  testslide/mock_constructor.py
  testslide/strict_mock.py
Labels: CLA Signed, enhancement

#190 Add release script
  RELEASE.md
  release.sh
Labels: CLA Signed
