Repository facebook/TestSlide, pull requests merged in 2020-04, with the labels that each got.

#132 [strict_mock] Support mocks in signature validation
  tests/strict_mock_testslide.py
  testslide/lib.py
  testslide/strict_mock.py
Labels: CLA Signed

#133 Fix memoize_before composition
  tests/dsl_unittest.py
  testslide/__init__.py
  testslide/dsl.py
Labels: CLA Signed

#134 Improve type validation tests
  tests/lib_testslide.py
  tests/matchers_unittest.py
  tests/mock_callable_testslide.py
  tests/sample_module.py
  tests/strict_mock_testslide.py
  testslide/lib.py
  testslide/mock_callable.py
  testslide/strict_mock.py
Labels: CLA Signed

#138 #135 Add ability to disable typechecking
  tests/mock_callable_testslide.py
  tests/strict_mock_testslide.py
  testslide/lib.py
  testslide/mock_callable.py
  testslide/strict_mock.py
Labels: CLA Signed

#140 Add type validation tests related to #138
  tests/mock_callable_testslide.py
  tests/strict_mock_testslide.py
Labels: CLA Signed

#144 Add tests for return value type validation & finish them
  tests/mock_callable_testslide.py
  tests/sample_module.py
  testslide/lib.py
  testslide/mock_callable.py
Labels: CLA Signed

#149 Take into account varargs in function signature validation
  tests/lib_testslide.py
  testslide/lib.py
Labels: CLA Signed

#147 Implement type checking for StrictMock non-callable attributes
  tests/strict_mock_testslide.py
  testslide/lib.py
  testslide/strict_mock.py
Labels: CLA Signed

#148 Add Long Formatter
  tests/cli_unittest.py
  testslide/cli.py
  testslide/runner.py
Labels: CLA Signed, enhancement

#152 Update mock_callable type validation docs
  docs/patching/mock_callable/index.rst
Labels: CLA Signed

#151 StrictMock type validation docs
  docs/patching/mock_async_callable/index.rst
  docs/strict_mock/index.rst
  testslide/strict_mock.py
Labels: CLA Signed

#146 Add type validation to mock constructor
  docs/patching/mock_constructor/index.rst
  tests/mock_constructor_testslide.py
  testslide/mock_constructor.py
Labels: CLA Signed

#153 Strict mock return type validation
  tests/strict_mock_testslide.py
  testslide/strict_mock.py
Labels: CLA Signed

#154 Add DSL debugging option
  docs/test_runner/index.rst
  tests/cli_unittest.py
  tests/dsl_unittest.py
  testslide/__init__.py
  testslide/cli.py
  testslide/runner.py
Labels: CLA Signed

#157 Add Coverage to build
  .coveragerc
  .gitignore
  .travis.yml
  Makefile
  README.md
  docs/test_runner/index.rst
  setup.py
  tests/cli_unittest.py
  testslide/__init__.py
Labels: CLA Signed

#158 Add Mypy
  .gitignore
  Makefile
  mypy.ini
  setup.py
  testslide/__init__.py
  testslide/dsl.py
  testslide/lib.py
  testslide/mock_callable.py
  testslide/mock_constructor.py
  testslide/patch_attribute.py
  testslide/strict_mock.py
Labels: CLA Signed

#164 [signature validation] Skip TypeVar signatures
  .gitignore
  docs/patching/mock_callable/index.rst
  tests/lib_testslide.py
  testslide/lib.py
Labels: CLA Signed

#166 Improve Makefile mechanics & output
  .travis.yml
  CONTRIBUTING.md
  Makefile
  tests/dsl_unittest.py
  tests/mock_constructor_testslide.py
  util/run_silent_if_successful.py
Labels: CLA Signed

#169 Fix unittest verbosity
  .travis.yml
  Makefile
Labels: Build, CLA Signed, bug

#167 Split mock_async_callable tests
  tests/mock_async_callable_testslide.py
  tests/mock_callable_testslide.py
  tests/sample_module.py
Labels: Build, enhancement

#163 Fix *args typing validation
  tests/lib_testslide.py
  tests/sample_module.py
  testslide/lib.py
  testslide/mock_callable.py
  testslide/mock_constructor.py
  testslide/strict_mock.py
Labels: CLA Signed

#168 Better handling of received signals
  .coveragerc
  Makefile
  testslide/cli.py
  util/run_silent_if_successful.py
Labels: Build, CLA Signed, enhancement

#171 Add missing copyright header
  util/run_silent_if_successful.py
Labels: CLA Signed

#172 Fix recursive type validation
  tests/lib_testslide.py
  tests/sample_module.py
  testslide/lib.py
Labels: CLA Signed, bug

#175 Make mock_callable respect type_validation
  testslide/mock_callable.py
Labels: CLA Signed, bug

#178 Fix inheritances
  testslide/runner.py
Labels: CLA Signed, bug

#179 Add tests for #175
  tests/mock_callable_testslide.py
Labels: CLA Signed, enhancement, mock(_async)_callable

#174 Fix circular dependency on 'coverage' command
  Makefile
Labels: Build, CLA Signed, bug

#181 Fix version file missing in distribution
  MANIFEST.in
  Makefile
  RELEASE.md
  docs/conf.py
  setup.py
  testslide/version
Labels: CLA Signed, bug

#176 Add mypy_clean
  Makefile
Labels: Build, CLA Signed, enhancement

#183 [lib] Ignore TypeVars also on return type
  tests/lib_testslide.py
  testslide/lib.py
Labels: CLA Signed
