Repository facebook/TestSlide, pull requests merged in 2020-10, with the labels that each got.

#246 Mega typechecking PR
  mypy.ini
  testslide/__init__.py
  testslide/cli.py
  testslide/dsl.py
  testslide/import_profiler.py
  testslide/lib.py
  testslide/matchers.py
  testslide/mock_callable.py
  testslide/mock_constructor.py
  testslide/patch.py
  testslide/patch_attribute.py
  testslide/runner.py
  testslide/strict_mock.py
Labels: CLA Signed

#251 fix #247 make _Config class a dataclass and remote type:ignore
  setup.py
  testslide/__init__.py
  testslide/cli.py
  testslide/runner.py
Labels: CLA Signed, hacktoberfest-accepted

#250 pin mypy version to avoid randomly breaking travis builds
  setup.py
Labels: CLA Signed

#253 Better bad setup error message
  testslide/mock_callable.py
Labels: CLA Signed

#252 Add colored stack traces
  mypy.ini
  setup.py
  tests/cli_unittest.py
  testslide/runner.py
Labels: Test Runner, enhancement

#255 Add Python 3.9 to build
  .travis.yml
  setup.py
Labels: CLA Signed

#256 Hide all TestSlide internal paths
  tests/cli_unittest.py
  testslide/runner.py
Labels: CLA Signed

#257 Tweak LongFormatter
  tests/cli_unittest.py
  testslide/runner.py
Labels: CLA Signed

#259 Expose PEP-561 typing information
  setup.py
  testslide/py.typed
Labels: CLA Signed

#262 downgrade pygments requirement to 2.6.1
  setup.py
Labels: CLA Signed

#260 testslide: remove unnecessary shebangs
  testslide/import_profiler.py
  testslide/lib.py
  testslide/matchers.py
Labels: CLA Signed

#261 util: use python3 for run_silent_if_successful
  Makefile
  util/run_silent_if_successful.py
Labels: CLA Signed
