Repository facebook/TestSlide, pull requests merged in 2020-07, with the labels that each got.

#200 add context about mocked function to type error to make debugging easier
  tests/lib_testslide.py
  testslide/lib.py
Labels: CLA Signed

#204 [global] don't load context when using getframeinfo
  tests/lib_testslide.py
  testslide/mock_constructor.py
  testslide/strict_mock.py
Labels: CLA Signed

#206 fix support for patching @property functions
  tests/patch_attribute_testslide.py
  tests/sample_module.py
  testslide/patch.py
Labels: CLA Signed

#205 make test summary nicer
  docs/patching/mock_callable/index.rst
  docs/test_runner/index.rst
  docs/testslide_dsl/async_support/index.rst
  docs/testslide_dsl/context_hooks/index.rst
  docs/testslide_dsl/contexts_and_examples/index.rst
  docs/testslide_dsl/shared_contexts/index.rst
  docs/testslide_dsl/skip_and_focus/index.rst
  testslide/runner.py
Labels: CLA Signed

#202 Print Errors with Progress formatter
  tests/cli_unittest.py
  testslide/runner.py
Labels: CLA Signed

#207 Add github templates for PR and Bug Report
  .github/ISSUE_TEMPLATE/Bug_Report.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: CLA Signed

#211 [lib] Fix forward references type checking
  tests/lib_testslide.py
  testslide/lib.py
Labels: CLA Signed

#215 Surface type errors
  docs/patching/mock_callable/index.rst
  docs/patching/mock_constructor/index.rst
  docs/strict_mock/index.rst
  tests/lib_testslide.py
  tests/mock_async_callable_testslide.py
  tests/mock_callable_testslide.py
  tests/mock_constructor_testslide.py
  tests/strict_mock_testslide.py
  testslide/lib.py
Labels: CLA Signed, enhancement

#219 Add exception cause
  tests/cli_unittest.py
  tests/sample_tests.py
  testslide/runner.py
Labels: CLA Signed, bug

#216 Fix double patch_attribute call unpatching
  tests/patch_attribute_testslide.py
  testslide/patch.py
  testslide/patch_attribute.py
Labels: CLA Signed

#203 kill signature_validation switch since type_validation is superior
  docs/patching/mock_callable/index.rst
  docs/strict_mock/index.rst
  tests/strict_mock_testslide.py
  testslide/strict_mock.py
Labels: CLA Signed

#213 [global] add isort and `make format`
  Makefile
  setup.py
  tests/cli_unittest.py
  tests/dsl_unittest.py
  tests/lib_testslide.py
  tests/matchers_unittest.py
  tests/mock_async_callable_testslide.py
  tests/mock_callable_testslide.py
  tests/mock_constructor_testslide.py
  tests/patch_attribute_testslide.py
  tests/sample_module.py
  tests/sample_tests.py
  tests/strict_mock_testslide.py
  tests/testcase_unittest.py
  testslide/__init__.py
  testslide/cli.py
  testslide/dsl.py
  testslide/lib.py
  testslide/mock_callable.py
  testslide/mock_constructor.py
  testslide/patch.py
  testslide/patch_attribute.py
  testslide/runner.py
  testslide/strict_mock.py
  util/run_silent_if_successful.py
Labels: CLA Signed

#220 Add TestSlide logo to README and docs
  README.md
  docs/index.rst
  docs/testslide_logo.png
Labels: CLA Signed

#221 Fix typo.
  docs/testslide_dsl/unittest_testcase_integration/index.rst
Labels: CLA Signed
